ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Impact pack deps
RUN apt-get install -y libgl1-mesa-glx libglib2.0-0

# Clean up to reduce image size
RUN apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

RUN pip3 install runpod requests

# Copy the build scripts
WORKDIR /
COPY --chmod=755 build/* ./

# Install ComfyUI
ARG TORCH_VERSION
ARG XFORMERS_VERSION
ARG INDEX_URL
ARG COMFYUI_COMMIT
RUN /install_comfyui.sh

# Support for the network volume
WORKDIR /ComfyUI
ADD src/extra_model_paths.yaml ./

# Install Application Manager
# ARG APP_MANAGER_VERSION
# RUN /install_app_manager.sh
# COPY app-manager/config.json /app-manager/public/config.json
# COPY --chmod=755 app-manager/*.sh /app-manager/scripts/

# Cleanup installation scripts
RUN rm -f /install_*.sh

# Remove existing SSH host keys
RUN rm -f /etc/ssh/ssh_host_*

# NGINX Proxy
# COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Set template version
ARG RELEASE
ENV TEMPLATE_VERSION=${RELEASE}

# Set the main venv path
ARG VENV_PATH
ENV VENV_PATH=${VENV_PATH}

# Copy the scripts
WORKDIR /
# COPY --chmod=755 scripts/* ./

# Copy runpod scripts
ADD src/start.sh src/rp_handler.py src/schemas src/workflows ./
RUN chmod +x /start.sh

# Start the container
SHELL ["/bin/bash", "--login", "-c"]
CMD [ "/start.sh" ]

