# Stage 1: Base image with common dependencies
FROM python:3.11-slim-bullseye AS base

# Prevents prompts from packages asking for user input during installation
ENV DEBIAN_FRONTEND=noninteractive
# Prefer binary wheels over source distributions for faster pip installations
ENV PIP_PREFER_BINARY=1
# Ensures output from python is printed immediately to the terminal without buffering
ENV PYTHONUNBUFFERED=1 
ENV PYTHONDONTWRITEBYTECODE=1

# Install Python, git and other necessary tools
RUN apt-get update && apt-get install -y \
    curl \   
    git \
    wget

# Impact pack deps
RUN apt-get install -y libgl1-mesa-glx libglib2.0-0

# Clean up to reduce image size
RUN apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

ENV COMFYUI_PATH="/runpod-volume/ComfyUI"
ENV PYTHONPATH="${COMFYUI_PATH}:$PYTHONPATH"

ENV PATH="${COMFYUI_PATH}:$PATH"

# Change working directory to ComfyUI
WORKDIR /runpod-volume/ComfyUI
# Support for the network volume
ADD src/extra_model_paths.yaml ./

# Go back to the root
WORKDIR /

RUN mkdir /logs
ARG OPENAI_API_KEY

# Copy runpod scripts
COPY src/schemas ./schemas
COPY src/workflows ./workflows
ADD src/start-network.sh ./start.sh 
ADD src/rp_handler.py src/upscaler.py src/upload.py ./
RUN chmod +x /start.sh

# Start the container
CMD /start.sh